### ISSUE TITLE
js

### ISSUE THREAD

**Issue by sentoxo** [miqez/RunForest#1]
Zacząłbyś używać prawdziwych języków a nie tylko ten podjęzyk java w wersji skryptowej :D

**Comment by miqez** [comment]
JavaScript jest spoko :D Wrzucaj coś nowego na Githuba :D

**Comment by Katsuatis** [comment]
Kuba zacząłbyś używać prawdziwych języków np. niemiecki ( ͡° ͜ʖ ͡°)

**Comment by sentoxo** [comment]
Ja, natürlich.
